{% set version = "0.0.1" %}

package:
  name: jb_tools
  version: {{ version }}

source:
  path: ../

build:
  number: 2
  entry_points:
    - buildit = jbscripts.buildjb:main
    - watchit = jbscripts.watch_build:main
    
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  build:
    - python ==3.7.*
    - click
    - watchdog

  run:
    - python
    - click
    - watchdog

test:
  imports:
    - jbscripts
  commands:
    - buildit build-jb --help
    - buildit build-nb --help
    - watchit watch-jb --help
    - watchit watch-nb --help

about:
  home: https://github.com/eoas-ubc/jb_tools
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: 'tools for working with myst and jupyter-book'
  description: |
    buildit wraps sphinx and jupyter-book
    watchit wraps watchdog

extra:
  recipe-maintainers:
    - phaustin
