{% set version = "0.1.3" %}

package:
  name: jb_tools
  version: {{ version }}

source:
  path: ../

build:
  number: 2
  entry_points:
    - ebp-build = jbscripts.buildjb:main
    - ebp-watch = jbscripts.watch_build:main
    
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  build:
    - python > 3.8
    - click
    - watchfiles

  run:
    - python
    - click
    - watchdog

test:
  imports:
    - jbscripts
  commands:
    - ebp-build jb --help
    - ebp-build nb --help
    - ebp-watch jb --help
    - ebp-watch nb --help

about:
  home: https://github.com/eoas-ubc/jb_tools
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: 'tools for working with myst and jupyter-books'
  description: |
    watch folders for changes and run jb or sphinx-build

extra:
  recipe-maintainers:
    - phaustin
