name: watchfiles
channels:
  - eoas_ubc
  - conda-forge
  - defaults
dependencies:
  - git
  - python>3.8
  - bz2file
  - jupyter-book
  - jupyter
  - jupyterlab
  - jupyter_contrib_nbextensions
  - notebook
  - pip
  - click
  - setuptools_scm
  - nodejs
  - watchfiles
# conda-lock --kind explicit --file environment.yml -p linux-64


